all: statuts ri charte fiche

statuts:
	xelatex statuts
	xelatex statuts

ri:
	xelatex ri
	xelatex ri

charte:
	xelatex charte
	xelatex charte

fiche:
	xelatex fiche
	xelatex fiche

clean:
	rm *.aux *.log *.toc *.out

