all: statuts ri charte charteTemp

statuts:
	xelatex statuts
	xelatex statuts

ri:
	xelatex ri
	xelatex ri

charteTemp:
	xelatex charteTemp
	xelatex charteTemp

charte:
	xelatex charte
	xelatex charte

clean:
	rm *.aux *.log *.toc *.out

